name: Deployment
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: |
        cd infrastructure
        terraform init

#    - name: "Configure AWS Credentials"
#      uses: aws-actions/configure-aws-credentials@v1
#      with:
#        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        aws-region: us-east-1

    - name: "Terraform apply"
      run: |
        cd infrastructure
        ./deploy.sh ${GITHUB_SHA}